name: endaft_core
description: The core library behind the EnDaft 'shared' library. Chock full of goodness within.
version: 0.0.1
homepage: https://endaft.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  path: ^1.8.1
  meta: ^1.7.0
  injector: ^2.0.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  aws_lambda_dart_runtime:
    git: https://github.com/katallaxie/aws-lambda-dart-runtime

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
  mocktail: ^0.2.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
