name: endaft_core
description: The core library behind the EnDaft 'shared' library. Chock full of goodness within.
version: 0.0.1
homepage: https://endaft.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
