name: endaft_core
description: The core library behind the EnDaft 'shared' library. Chock full of
  goodness within.
version: 0.0.2
homepage: https://endaft.dev
repository: https://github.com/endaft/endaft-core
issue_tracker: https://github.com/endaft/endaft-core/issues
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  http: ^0.13.4
  path: ^1.8.0
  meta: ^1.7.0
  matcher: ^0.12.11
  mocktail: ^0.3.0
  injector: ^2.0.0
  equatable: ^2.0.3
  collection: ^1.15.0
  aws_s3_api: ^1.2.0
  json_annotation: ^4.4.0
  aws_lambda_dart_runtime: ^1.1.0
  amazon_cognito_identity_dart_2: ^1.0.5
dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
  analyzer: ^3.3.1
  coverage: ^1.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
