name: endaft_core
description: The core library behind the EnDaft 'shared' library. Chock full of
  goodness within.
version: 0.0.3
homepage: https://endaft.dev
repository: https://github.com/endaft/endaft-core
issue_tracker: https://github.com/endaft/endaft-core/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ">=3.0.0 <4.0.0"
  aws_lambda_dart_runtime: ">=1.1.0 <2.0.0"
  aws_s3_api: ">=1.2.0 <3.0.0"
  collection: ">=1.16.0 <2.0.0"
  equatable: ">=2.0.0 <3.0.0"
  http: ">=0.13.0 <1.0.0"
  injector: ">=2.0.0 <3.0.0"
  json_annotation: ">=4.6.0 <5.0.0"
  matcher: ">=0.12.0 <1.0.0"
  meta: ">=1.8.0 <2.0.0"
  mocktail: ">=0.3.0 <1.0.0"
  path: ">=1.8.0 <2.0.0"
  uuid: ">=3.0.0 <4.0.0"

dev_dependencies:
  analyzer: ">=4.7.0 <6.0.0"
  build_runner: ">=2.2.0 <3.0.0"
  build_test: ">=2.1.5 <3.0.0"
  coverage: ">=1.5.0 <2.0.0"
  json_serializable: ">=6.0.0 <7.0.0"
  lints: ">=2.0.0 <3.0.0"
  test: ">=1.0.0 <2.0.0"
